spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
    #发送确认
    publisher-confirms: true
    #无效路由返回
    publisher-returns: true
    template:
      mandatory: true
server:
  port: 21000