
rocketmq:
  name-server: 192.168.220.128:9876
  producer:
    group: producer-group
    access-key: rocketmq2
    secret-key: 12345678
    retry-times-when-send-failed: 2
  consumer:
    access-key: rocketmq2
    secret-key: 12345678

spring:
  application:
    name: rocketmq
server:
  port: 8080
logging:
  level:
    root: info